version: "3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: mosaic_dev
      POSTGRES_USER: mosaic
      POSTGRES_PASSWORD: MDaUA2P4ZbkJPCKEM
    ports:
      - "5432:5432"

  api:
    image: node:10
    environment:
        DATABASE_URL: postgres://mosaic:MDaUA2P4ZbkJPCKEM@postgres/mosaic_dev
        USING_DOCKER: "true"
        NODE_ENV: "${NODE_ENV:-development}"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./server:/data
    command: "bash -c 'sleep 3 && cd /data && yarn --production=false && yarn run db:migrate && yarn run dev'"
    depends_on:
      - postgres

  web:
    image: node:10
    environment:
        USING_DOCKER: "true"
        NODE_ENV: "${NODE_ENV:-development}"
    depends_on:
      - api
    volumes:
      - ./client:/data
    ports:
      - "3000:3000"
    command: "bash -c 'cd /data && yarn --production=false && yarn run start'"
