import * as _ from "lodash";
const uuidv4 = require("uuid/v4");

export function extractMaliciousAnswerValueFromMaliciousQuestionAndJudgeQuestion(
  maliciousQuestionValue,
  judgeQuestionValue,
) {
  const honestPointerId = _.get(
    maliciousQuestionValue,
    "[0].nodes[3].data.pointerId",
  );
  const firstPointerId = _.get(
    judgeQuestionValue,
    "[0].nodes[3].data.pointerId",
  );
  const secondPointerId = _.get(
    judgeQuestionValue,
    "[0].nodes[5].data.pointerId",
  );

  // maliciousQuestionValue and judgeQuestionValue are generated by files in lib/models/helpers
  // and should have the structure to support the previous uses of _.get

  // But we'll check to make sure and throw an Error (which Sentry will log)
  // if any of these pointer id values are missing.

  if (!honestPointerId || !firstPointerId || !secondPointerId) {
    throw Error(
      `Slate structure of questions incorrect:
      honestPointerId: ${honestPointerId},
      firstPointerId: ${firstPointerId},
      secondPointerId: ${secondPointerId}`,
    );
  }

  const maliciousPointerId =
    firstPointerId === honestPointerId ? secondPointerId : firstPointerId;

  const blockValue = [
    {
      object: "block",
      type: "line",
      isVoid: false,
      data: {},
      nodes: [
        {
          object: "text",
          leaves: [
            {
              object: "leaf",
              text: "A ",
              marks: [],
            },
          ],
        },
        {
          object: "inline",
          type: "pointerImport",
          isVoid: true,
          data: {
            internalReferenceId: uuidv4(),
            pointerId: maliciousPointerId,
          },
        },
        {
          object: "text",
          leaves: [{ object: "leaf", text: "", marks: [] }],
        },
      ],
    },
  ];

  return blockValue;
}
