require('dotenv').config();

const {
  ID_OF_TYPICAL_USER_FOR_TESTING,
  ID_OF_ADMIN_FOR_TESTING,
  ID_OF_ORACLE_FOR_TESTING,
  ID_OF_ADMIN_AND_ORACLE_FOR_TESTING,
} = process.env;

export {
  ID_OF_TYPICAL_USER_FOR_TESTING,
  ID_OF_ADMIN_FOR_TESTING,
  ID_OF_ORACLE_FOR_TESTING,
  ID_OF_ADMIN_AND_ORACLE_FOR_TESTING,
};
